#! /usr/bin/env python2

import sys, json, struct
import hashlib
import os
import recoll
import traceback
from Queue import Queue, Empty
from threading import Thread

try:
  from recoll import rclconfig
except:
  import rclconfig

config = rclconfig.RclConfig()
webqueuedir = config.getConfParam("webqueuedir")
if not webqueuedir:
    webqueuedir = "~/.recollweb/ToIndex"
webqueuedir = os.path.expanduser(webqueuedir)

# Read a message from stdin and decode it.
def queue_messages(queue):
  while True:
    rawLength = sys.stdin.read(4)
    if len(rawLength) == 0:
        sys.exit(0)
    messageLength = struct.unpack('@I', rawLength)[0]
    message = sys.stdin.read(messageLength)
    queue.put(json.loads(message));

def encodeMessage(messageContent):
  encodedContent = json.dumps(messageContent)
  encodedLength = struct.pack('@I', len(encodedContent))
  return {'length': encodedLength, 'content': encodedContent}

# Send an encoded message to stdout
def sendMessage(encodedMessage):
  sys.stdout.write(encodedMessage['length'])
  sys.stdout.write(encodedMessage['content'])
  sys.stdout.flush()

def archive(message):
  path = webqueuedir
  url = message["url"]
  name = "firefox-recoll-web-" + hashlib.md5(url.encode('utf-8')).hexdigest()
  html = open(os.path.join(path, name), "w")
  html.write(message["page"].encode(encoding='utf-8'))
  html.close()
  meta = open(os.path.join(path, '.' + name), "w")
  meta_content = [url,
                  "WebHistory",
                  message["mime"],
                  "k:_unindex:encoding=" + message["charset"],
                  ""]
  meta.write("\n".join(meta_content))
  meta.close()

def search(message):
  db = recoll.connect()
  query = db.query()
  query_string = message['query']
  query.execute('rclbes:BGL ' + query_string)
  if query.rowcount == 0:
    return
  result = []
  for doc in query:
    entry = doc.items()
    entry['snippet'] = query.highlight(query.makedocabstract(doc))
    entry['query'] = query_string
    sendMessage(encodeMessage(entry))

def omnisearch(message):
  db = recoll.connect()
  query = db.query()
  query_string = message['query']
  query.execute('rclbes:BGL ' + query_string)
  if query.rowcount == 0:
    sendMessage(encodeMessage(message))
    return
  result = []
  for doc in query:
    entry = doc.items()
    result.append(entry)
  message['result'] = result
  sendMessage(encodeMessage(message))

queue = Queue()
thread = Thread(target=queue_messages, args=(queue,))
thread.daemon = True
thread.start()

# Always listen for messages
while True:
  message = queue.get(block=True)
  action = message["type"]
  try:
    if action == "archive":
      archive(message)
    elif action == "search":
      search(message)
    elif action == "omnibox":
      omnisearch(message)
  except:
    error = traceback.format_exc()
    sys.stderr.write(error)
    sys.stderr.flush()
